# Generated by Django 5.0.2 on 2024-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_category_icon_alter_server_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="images/banners/"),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to="images/category/"),
        ),
    ]
