# Generated by Django 5.0.2 on 2024-02-17 20:07

import server.validator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_channel_banner_channel_icon_alter_category_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="icon",
        ),
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="images/banners/"),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/icons",
                validators=[
                    server.validator.validateIconImageSize,
                    server.validator.validateImageFileExtension,
                ],
            ),
        ),
    ]
