version: '3.8'
services: 

  redis:
    container_name: redis
    image: redis
    ports: 
      - 6379:6379
    command: redis-server --loglevel warning
    restart: always
  worker1:
    container_name: worker1
    build: .
    # command: celery -A core worker --loglevel=info
    command: celery -A core.celery worker --pool=prefork --concurrency=5 --autoscale=10,3 -l info && celery -A core beat -l info

    env_file: .env
    volumes:
      - ./core:/app
    depends_on:
      - backend1
      - redis

  backend1:
    build: .
    container_name: backend1
    command: python manage.py runserver 0.0.0.0:8000
    # command: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput gunicorn -w 8 core.wsgi:application --bind 0.0.0.0:8000
    # command: daphne core.asgi:application --bind 0.0.0.0 -p 8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DEBUG=False
    restart: always
    depends_on:
      - redis
      - db
    # networks:
    #   - nginxnetwork
  

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file: .env
 

 

 
#   master:
#     image: locustio/locust
#     ports:
#      - "8089:8089"
#     restart: always
#     volumes:
#       - ./locust:/mnt/locust
#     command: -f /mnt/locust/locustfile.py  --master -H http://127.0.0.1:80/
  
#   worker:
#     image: locustio/locust
#     restart: always
#     volumes:
#       - ./locust:/mnt/locust
#     command: -f /mnt/locust/locustfile.py --worker --master-host master

networks:
  nginxnetwork:
    external: true