# Generated by Django 3.2.4 on 2021-07-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilefeeditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statustext', models.CharField(max_length=255)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
