# Generated by Django 3.2.9 on 2022-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('testscore', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
