version: '3.8'
services:
  app1:
    # container_name: asyncsync
    build:
      context: ./asyncsync
      dockerfile: Dockerfile
    volumes:
     - ./asyncsync:/app
    restart: always
    # ports:
    #   - "8000:8000"
    networks:
      - nginxnetwork
    # command: gunicorn -w 10 asyncsync.wsgi:application --bind 0.0.0.0:8001
    command: daphne asyncsync.asgi:application -b 0.0.0.0 -p 8001

  # app2:
  #   # container_name: asyncsync
  #   build:
  #     context: ./asyncsync
  #     dockerfile: Dockerfile
  #   volumes:
  #    - ./asyncsync:/app

  #   restart: always
  #   # ports:
  #   #   - "8002:8000"
  #   networks:
  #     - nginxnetwork
  #   # command: gunicorn -w 2 asyncsync.wsgi:application --bind 0.0.0.0:8002
  #   command: daphne asyncsync.asgi:application -b 0.0.0.0 -p 8002

  # app3:
  #   # container_name: asyncsync
  #   build:
  #     context: ./asyncsync
  #     dockerfile: Dockerfile
  #   volumes:
  #    - ./asyncsync:/app
  #   restart: always
  #   # ports:
  #   #   - "8003:8000"
  #   networks:
  #     - nginxnetwork
  #   # command: gunicorn -w 2 asyncsync.wsgi:application --bind 0.0.0.0:8003
  #   command: daphne asyncsync.asgi:application -b 0.0.0.0 -p 8003

  # app4:
  #   # container_name: asyncsync
  #   build:
  #     context: ./asyncsync
  #     dockerfile: Dockerfile
  #   volumes:
  #    - ./asyncsync:/app

  #   restart: always
  #   # ports:
  #   #   - "8004:8000"
  #   networks:
  #     - nginxnetwork
  #   # command: gunicorn -w 2 asyncsync.wsgi:application --bind 0.0.0.0:8004
  #   command: daphne asyncsync.asgi:application -b 0.0.0.0 -p 8004
 
      
 
networks:
  nginxnetwork:
    external: true