# Generated by Django 4.0.4 on 2022-06-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnumber', models.CharField(max_length=10)),
                ('operatingairlines', models.CharField(max_length=20)),
                ('departurecity', models.CharField(max_length=20)),
                ('arrivalcity', models.CharField(max_length=20)),
                ('dateofdeparture', models.DateField()),
                ('estimatedtimeofdeparture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passengar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight')),
                ('passengar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightapp.passengar')),
            ],
        ),
    ]
